file(READ "${CMAKE_SOURCE_DIR}/VERSION" VERSION_RAW)

string(REGEX MATCH "([0-9]+)\.([0-9]+)\.([0-9]+)(-([a-zA-Z0-9_-]+))?" _ "${VERSION_RAW}")
set(RESIN_VERSION_MAJOR     ${CMAKE_MATCH_1})
set(RESIN_VERSION_MINOR     ${CMAKE_MATCH_2})
set(RESIN_VERSION_PATCH     ${CMAKE_MATCH_3})
set(RESIN_VERSION_REVISION  ${CMAKE_MATCH_5})

option(NIGHTLY "Append the commit short hash to the version" OFF)
if (NIGHTLY)
  find_package(Git REQUIRED)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE RESIN_VERSION_REVISION
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
endif()

if (RESIN_VERSION_REVISION)
  set(RESIN_VERSION "${RESIN_VERSION_MAJOR}.${RESIN_VERSION_MINOR}.${RESIN_VERSION_PATCH}-${RESIN_VERSION_REVISION}")
else()
  set(RESIN_VERSION "${RESIN_VERSION_MAJOR}.${RESIN_VERSION_MINOR}.${RESIN_VERSION_PATCH}")
endif()
