name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win64
          - win32
        include:
          - name: win64
            os: windows-2022
            cmake_opts: -A x64
          - name: win32
            os: windows-2022
            cmake_opts: -A Win32
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'
    - name: Setup
      run: |
        mkdir build
    - name: Build
      run: |
        cmake .. ${{ matrix.cmake_opts }}
        cmake --build . --config Release
      working-directory: ./build
    - name: Package
      run: |
        python tools/package.py ${{ matrix.name }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.name }}
        path: dist
  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download win64
        uses: actions/download-artifact@v1
        with:
          name: win64
          path: dist
      - name: Download win32
        uses: actions/download-artifact@v1
        with:
          name: win32
          path: dist
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
